### ISSUE TITLE
Model test fails on custom bounds on Sentinel 2A tiles

### ISSUE THREAD

**Issue by purijs** [lanha/DSen2#29]
I'm trying to pass custom bounds for a complete sentinel-2A tile and also tried without passing the `rio` param as I want to run on full tile, however it is failing with this error:

```
2020-10-27 19:50:46.779614: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_110.dll
Selected UTM Zone: UTM 11N
Selected pixel region: xmin=96, ymin=96, xmax=9995, ymax=9995:
Image size: width=9900 x height=9900
Selected 10m bands: B4 B3 B2 B8
Selected 20m bands: B5 B6 B7 B8A B11 B12
Selected 60m bands: B1 B9
Loading selected data from: Bands B2, B3, B4, B8 with 10m resolution, UTM 11N
Loading selected data from: Bands B5, B6, B7, B8A, B11, B12, AOT, CLD, SCL, SNW, WVP with 20m resolution, UTM 11N
ERROR 1: Stream too short

ERROR 1: opj_get_decoded_tile() failed
ERROR 1: Stream too short

ERROR 1: Stream too short

ERROR 1: Stream too short

ERROR 1: Stream too short

ERROR 1: Stream too short

ERROR 1: opj_get_decoded_tile() failed
ERROR 1: opj_get_decoded_tile() failed
ERROR 1: opj_get_decoded_tile() failed
ERROR 1: opj_get_decoded_tile() failed
ERROR 1: opj_get_decoded_tile() failed
Traceback (most recent call last):
  File ".\s2_tiles_supres.py", line 319, in <module>
    data20 = np.rollaxis(
  File "<__array_function__ internals>", line 5, in rollaxis
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 1259, in rollaxis
    n = a.ndim
AttributeError: 'NoneType' object has no attribute 'ndim'
```

**Comment by lanha** [comment]
Hello, it's unlikely that it will work for Sentinel level 2A data. Please check this branch for L2A: https://github.com/up42/DSen2

**Comment by purijs** [comment]
The other repo testing scripts are little different, can you share a snippet on how to run a pre-trained model, it has different params as well
