### ISSUE TITLE
Code from up42 / DSen2 not working for 2A tiles

### ISSUE THREAD

**Issue by purijs** [lanha/DSen2#30]
I;m trying the following line to test on S2A tiles:

`python .\s2_tiles_supres.py --clip_to_aoi 100,100,5000,5000 D:\work\explore\convert-sentinel2-to-cogs\extract\S2A_MSIL2A_20200505T181921_N0214_R127_T11SPA_20200505T222608.SAFE\MTD_MSIL2A.xml`

Error

```
Traceback (most recent call last):
  File ".\s2_tiles_supres.py", line 212, in <module>
    Superresolution(
  File ".\s2_tiles_supres.py", line 178, in process
    data10, data20, data60, coord, pr_10m = self.start()
  File ".\s2_tiles_supres.py", line 73, in start
    data_list = self.get_data()
  File "..\utils\data_utils.py", line 65, in get_data
    LOGGER.info(f"Data path is {data_path}")
UnboundLocalError: local variable 'data_path' referenced before assignment
```

**Comment by lanha** [comment]
This repo does not support level 2A unfortunately.
