### ISSUE TITLE
Troubleshoot Getting Started

### ISSUE THREAD

**Issue by baconised** [lanha/DSen2#46]
```
cillian@cillian-VirtualBox:~/Downloads/DSen2-master$ python3 testing/supres.py output/MTD_MSIL1C.xml output/output_file.tif --roi_x_y "100,100,2000,2000"
```
Illegal instruction (core dumped)

```
cillian@cillian-VirtualBox:~/Downloads/DSen2-master$ sudo python3 testing/supres.py output/MTD_MSIL1C.xml output/output_file.tif --roi_x_y "100,100,2000,2000"
[sudo] password for 
```
Traceback (most recent call last):
  File "/home/cillian/Downloads/DSen2-master/testing/supres.py", line 11, in <module>
    from utils.DSen2Net import s2model
  File "/home/cillian/Downloads/DSen2-master/utils/DSen2Net.py", line 2, in <module>
    import keras
ModuleNotFoundError: No module named 'keras'

------------------------------------------------------------------------------------------------------------------------------------------------------
I am getting this problem. Can anyone help here!? I have everything installed in my ubuntu VM but this is just not running. :// Can you please elaborate the installation process on ubuntu or windows?

On windows -> gdal is not being installed because it cant create a wheel file and the options given online are no more existing.
On Linux -> I am getting above error.

**Comment by lanha** [comment]
did you use conda to install the dependencies?
